# ==================================
# Publications for the current grant
# ==================================
# The Trees in the Forest: Characterizing Computing Students' Individual Help-Seeking Approaches
- id: https://doi.org/10.1145/3632620.3671099
  description: This paper investigates the help-seeking behaviors of individual computing students across various course contexts, identifying which aspects are consistent for each student (individual-driven) and which vary depending on the course (context-driven), aiming to enhance personalized educational support strategies.  
  image: images/publication_images/doi.org_10.1145_3632620.3671099.png

# ==================================
# Below are all other publications
# ==================================
# What Drives Students to Office Hours: Individual Differences and Similarities
- id: https://doi.org/10.1145/3545945.3569777
  image: images/publication_images/doi.org_10.1145_3545945.3569777.png

# UPIC a Problem-Solving Framework: Understand, Plan, Implement, and Correctness/Debugging
- id: https://doi.org/10.1145/3501709.3544286
  image: images/publication_images/doi.org_10.1145_3501709.3544286.png

# Exploring Novice Programmers' Testing Behavior: A First Step to Define Coding Struggle
- id: https://doi.org/10.1145/3626252.3630851
  image: images/publication_images/doi.org_10.1145_3626252.3630851.png

# Using Survival Analysis to Model Students' Patience in Online Office Hour Queues
- id: https://doi.org/10.1145/3626253.3635517
  image: images/publication_images/doi.org_10.1145_3626253.3635517.png

# Observations on Student Help-Seeking Behaviors in Introductory Computer Science Courses
- id: https://doi.org/10.1145/3545947.3576325
  image: images/publication_images/no_img.png

# Too long to wait and not much to do: Modeling student behaviors while waiting for help in online office hours.
- id: https://par.nsf.gov/biblio/10392589
  image: images/publication_images/par.nsf.gov_biblio_10392589.png

# Who Should I Help Next? Simulation of Office Hours Queue Scheduling Strategy in a CS2 Course
- id: https://doi.org/10.5281/zenodo.12729866
  image: images/publication_images/doi.org_10.5281_zenodo.12729866.png
  publisher: International Educational Data Mining Society
  date: '2024-07-12'

# Academic Help Seeking Patterns in Introductory Computer Science Courses.
- id: http://dx.doi.org/10.18260/1-2--41526
  image: images/publication_images/dx.doi.org_10.18260_1-2--41526.png

# You asked, now what? Modeling Students’ Help-Seeking and Coding actions from Re- quest to Resolution
- id: https://eric.ed.gov/?id=EJ1373162
  image: images/publication_images/eric.ed.gov_EJ1373162.png

# Assessment of Self-Identified Learning Struggles in CS2 Programming Assignments
- id: https://doi.org/10.1145/3587102.3588786
  image: images/publication_images/doi.org_10.1145_3587102.3588786.png

# Don't Just Paste Your Stacktrace: Shaping Discussion Forums in Introductory CS Courses
- id: https://doi.org/10.1145/3478432.3499110
  image: images/publication_images/no_img.png

# Who uses office hours? a comparison of in-person and virtual office hours utilization.
- id: https://doi.org/10.1145/3478431.3499334
  image: images/publication_images/doi.org_10.1145_3478431.3499334.png

# Admitting You Have a Problem Is the First Step: Modeling When and Why Students Seek Help in Programming Assignments
- id: https://eric.ed.gov/?id=ED624046
  image: images/publication_images/eric.ed.gov_ED624046.png

# Automatically Classifying Student Help Requests: A Multi-Year Analysis.
- id: https://eric.ed.gov/?id=ED615496
  image: images/publication_images/eric.ed.gov_ED615496.png
  
# My digital hand: A tool for scaling up one-to-one peer teaching in support of computer science learning.
- id: https://doi.org/10.1145/3017680.3017800
  image: images/publication_images/doi.org_10.1145_3017680.3017800.png

# Deconstructing the discussion forum: Student questions and computer science learning.
- id: https://doi.org/10.1145/3017680.3017745
  image: images/publication_images/doi.org_10.1145_3017680.3017745.png

# S3xE7: Class Forums with Amogh Mannekote
- id: https://csedpodcast.org/blog/s3e7_class_forums/
  image: images/publication_images/csed_podcast.png
  title: 'CSED Podcast Episode - S3xE7: Class Forums with Amogh Mannekote'
  authors:
  - Kristin Stephens-Martinez
  - Amogh Mannekote
  publisher: Produced by Kristin Stephens-Martinez and Amarachi Anakaraonye

# S3xE9: Peer Teaching Summit at SIGCSE TS 2022
- id: https://csedpodcast.org/blog/s3e9_peer_teaching/
  image: images/publication_images/csed_podcast.png
  title: 'CSED Podcast Episode - S3xE9: Peer Teaching Summit at SIGCSE TS 2022'
  authors:
  - Kristin Stephens-Martinez
  - Sarah Heckman
  publisher: Produced by Kristin Stephens-Martinez and Amarachi Anakaraonye
