# This is for the current grant
# The Trees in the Forest: Characterizing Computing Students' Individual Help-Seeking Approaches
- id: https://doi.org/10.1145/3632620.3671099
  image: https://duke.box.com/shared/static/n1265pzl4c75ezru5zvx3jfk2jyo6icr.png

# What Drives Students to Office Hours: Individual Differences and Similarities
- id: https://doi.org/10.1145/3545945.3569777
  image: https://duke.box.com/shared/static/lzynqrpx2m0dvj2vkgy9hojt2ytraal2.png

# UPIC a Problem-Solving Framework: Understand, Plan, Implement, and Correctness/Debugging
- id: https://doi.org/10.1145/3501709.3544286
  image: https://duke.box.com/shared/static/9k4hzdh51za59kj5afua2h1vlksrs1a5.png

# Don't Just Paste Your Stacktrace: Shaping Discussion Forums in Introductory CS Courses
- id: https://doi.org/10.1145/3478432.3499110

# Exploring Novice Programmers' Testing Behavior: A First Step to Define Coding Struggle
- id: https://doi.org/10.1145/3626252.3630851
  image: https://duke.box.com/shared/static/dabygh9d7jyxmulro1pjepv6km1qe1wn.png

# Using Survival Analysis to Model Students' Patience in Online Office Hour Queues
- id: https://doi.org/10.1145/3626253.3635517
  image: https://duke.box.com/shared/static/pkn1ziq3badfyftfusd1vj4xb0dvbaka.png

# Observations on Student Help-Seeking Behaviors in Introductory Computer Science Courses
- id: https://doi.org/10.1145/3545947.3576325

# Too long to wait and not much to do: Modeling student behaviors while waiting for help in online office hours.
- id: https://par.nsf.gov/biblio/10392589

# Who Should I Help Next? Simulation of Office Hours Queue Scheduling Strategy in a CS2 Course
- id: https://doi.org/10.5281/zenodo.12729866
  image: https://duke.box.com/shared/static/fwsap9gen6ty2yc4qefb3gmlyj8w2heq.png

# Academic Help Seeking Patterns in Introductory Computer Science Courses.
- id: http://dx.doi.org/10.18260/1-2--41526
  image: https://duke.box.com/shared/static/5kysrc8likp34rpoj3aduu503f7zfkdp.png

# You asked, now what? Modeling Students’ Help-Seeking and Coding actions from Re- quest to Resolution
- id: https://eric.ed.gov/?q=You+asked%2c+now+what%3f+Modeling+Students’+Help-Seeking+and+Coding+actions+from+Re-+quest+to+Resolution&id=EJ1373162
#  image: https://duke.box.com/shared/static/5kysrc8likp34rpoj3aduu503f7zfkdp.png


#https://par.nsf.gov/biblio/10392589
#https://www.researchgate.net/publication/371072286_Too_long_to_wait_and_not_much_to_do_Modeling_student_behaviors_while_waiting_for_help_in_online_office_hours

- id: doi:10.1371/journal.pcbi.1007128
  type: paper
  description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  date: 2020-12-4
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      text: Manuscript Source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/
  tags:
    - open science
    - collaboration
  repo: greenelab/meta-review
