name: build-site
run-name: build live site

on:
  # run when called from another workflow
  workflow_call:

  # run if user manually requests it
  workflow_dispatch:

# variables
env:
  PREVIEWS_FOLDER: preview

permissions:
  contents: write

jobs:
  build-site:
    # ubuntu-latest
    runs-on: ubuntu-24.04 #ubuntu-22.04 

    steps:
      # for debugging
      - uses: crazy-max/ghaction-dump-context@v2

      - name: Checkout branch contents
        uses: actions/checkout@v4

      - name: Manually install Ruby 3.1.4 if missing (Ubuntu 24.04 workaround)
        run: |
          if [ ! -x /opt/hostedtoolcache/Ruby/3.1.4/x64/bin/ruby ]; then
            sudo apt-get update
            sudo apt-get install -y build-essential libssl-dev libreadline-dev zlib1g-dev git curl
            git clone https://github.com/rbenv/ruby-build.git
            sudo mkdir -p /opt/hostedtoolcache/Ruby/3.1.4/x64
            ./ruby-build/bin/ruby-build 3.1.4 /opt/hostedtoolcache/Ruby/3.1.4/x64
            sudo touch /opt/hostedtoolcache/Ruby/3.1.4/x64.complete
          fi

      - name: Add manually installed Ruby to PATH
        run: |
          echo "/opt/hostedtoolcache/Ruby/3.1.4/x64/bin" >> $GITHUB_PATH

      - name: Install Ruby packages
        uses: ruby/setup-ruby@v1.172.0
        with:
          ruby-version: "3.1"
          bundler-cache: true

      - name: Get Pages url
        id: pages
        uses: actions/configure-pages@v4

      # for debugging
      - if: runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

      - name: Set root url
        run: |
          printf "\n\nurl: ${{ steps.pages.outputs.origin }}" >> _config.yaml

      - name: Build live version of site
        run: |
          JEKYLL_ENV=production bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path || '' }}"

      - name: Commit live site to Pages branch
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          folder: _site
          clean-exclude: ${{ env.PREVIEWS_FOLDER }}
          force: false
