name: build-preview
run-name: build pull request preview

on:
  # run when called from another workflow
  workflow_call:

  # run if user manually requests it
  workflow_dispatch:

env:
  PREVIEWS_FOLDER: preview

permissions:
  contents: write
  pull-requests: write

jobs:
  build-preview:
    runs-on: ubuntu-24.04

    steps:
      # for debugging
      - uses: crazy-max/ghaction-dump-context@v2

      - name: Checkout branch contents
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}

      - name: Install Ruby 3.1.4 manually using ruby-build
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential libssl-dev libreadline-dev zlib1g-dev git curl
          git clone https://github.com/rbenv/ruby-build.git
          export PREFIX="$HOME/.rbenv/versions/3.1.4"
          ./ruby-build/bin/ruby-build 3.1.4 "$PREFIX"
          echo "$PREFIX/bin" >> $GITHUB_PATH

      - name: Install bundler and install dependencies
        run: |
          ruby -v
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Get Pages url
        id: pages
        uses: actions/configure-pages@v4

      - name: Build preview version of site
        run: |
          JEKYLL_ENV=production bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path || '' }}/${{ env.PREVIEWS_FOLDER }}/pr-${{ github.event.number }}"

      - name: Commit preview to Pages branch
        uses: rossjrw/pr-preview-action@v1.4.7
        with:
          source-dir: _site
          umbrella-dir: ${{ env.PREVIEWS_FOLDER }}
